### ISSUE TITLE
ReferenceError: XeroStrategy is not defined

### ISSUE THREAD

**Issue by madeshvhabile** [octoblu/passport-xero#1]
I tried to authenticate the Xero application but I got the reference Error
ReferenceError: XeroStrategy is not defined
   at /home/madesh/Downloads/xero/ToolModule/server.js:38:20
   at Layer.handle [as handle_request] (/home/madesh/Downloads/xero/ToolModule/node_modules/express/lib/router/layer.js:95:5)
   at next (/home/madesh/Downloads/xero/ToolModule/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/home/madesh/Downloads/xero/ToolModule/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/home/madesh/Downloads/xero/ToolModule/node_modules/express/lib/router/layer.js:95:5)
   at /home/madesh/Downloads/xero/ToolModule/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/home/madesh/Downloads/xero/ToolModule/node_modules/express/lib/router/index.js:330:12)
   at next (/home/madesh/Downloads/xero/ToolModule/node_modules/express/lib/router/index.js:271:10)
   at SendStream.error (/home/madesh/Downloads/xero/ToolModule/node_modules/serve-static/index.js:121:7)
   at emitOne (events.js:77:13)

**Comment by royvandewater** [comment]
Hi @madeshvhabile, could you please post the contents of your server.js to help us debug why this is happening? It sounds like you might not be requiring the module before you're using it. I'll update the readme to show you what I mean.

**Comment by royvandewater** [comment]
I updated the Readme, do you have this require line at the top of your server.js file?

https://github.com/octoblu/passport-xero/commit/c2f22e707c4f164b96e3cefd91e817ff6eeadae8
